//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Muayene
    {
        public System.DateTime Tarih { get; set; }
        public string TCno { get; set; }
        public string Branşı { get; set; }
        public string Doktoru { get; set; }
        public string İlac { get; set; }
    
        public virtual Doktor Doktor { get; set; }
        public virtual Hasta Hasta { get; set; }
        public virtual İlaç İlaç { get; set; }
    }
}
